{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 0", "trace": "self = <Tests.MarkDemo.test_marks.TestMarks object at 0x7fe15656ebe0>\n\n    @pytest.mark.xfail\n    def test_xfail(self):\n        \"\"\"\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        \"\"\"\n>       assert 0\nE       assert 0\n\nTests/MarkDemo/test_marks.py:44: AssertionError"}, "description": "\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        ", "start": 1616417751654, "stop": 1616417751654, "uuid": "10a7014c-3eb1-4e6f-94a9-586fd3760a80", "historyId": "4b1032b5ae3cf8de3f092441142afaef", "testCaseId": "0f6876dbdc5c7111fe8b6aee60d1a131", "fullName": "Tests.MarkDemo.test_marks.TestMarks#test_xfail", "labels": [{"name": "feature", "value": "pytest标记与分组"}, {"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "Tests.MarkDemo"}, {"name": "suite", "value": "test_marks"}, {"name": "subSuite", "value": "TestMarks"}, {"name": "host", "value": "gilbertdeMacBook-Pro.local"}, {"name": "thread", "value": "59090-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.MarkDemo.test_marks"}]}