{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "XFAIL\n\nAssertionError: assert 0", "trace": "self = <Tests.MarkDemo.test_marks.TestMarks object at 0x7fc40dd6cd30>\n\n    @pytest.mark.xfail\n    def test_xfail(self):\n        \"\"\"\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        \"\"\"\n>       assert 0\nE       assert 0\n\nTests/MarkDemo/test_marks.py:42: AssertionError"}, "description": "\n        Indicate that you expect it to fail\n        这条用例失败时，测试结果被标记为xfail（expected to fail），并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed（unexpectedly passing）\n        ", "start": 1616410505776, "stop": 1616410505776, "uuid": "843a93f0-dcdf-472f-8cf1-6703f06ddfba", "historyId": "4b1032b5ae3cf8de3f092441142afaef", "testCaseId": "0f6876dbdc5c7111fe8b6aee60d1a131", "fullName": "Tests.MarkDemo.test_marks.TestMarks#test_xfail", "labels": [{"name": "tag", "value": "@pytest.mark.xfail"}, {"name": "parentSuite", "value": "Tests.MarkDemo"}, {"name": "suite", "value": "test_marks"}, {"name": "subSuite", "value": "TestMarks"}, {"name": "host", "value": "gilbertdeMacBook-Pro.local"}, {"name": "thread", "value": "52161-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.MarkDemo.test_marks"}]}